class BaseBackendAPIError(Exception): ...


class AuthError(BaseBackendAPIError): ...


class RequestError(BaseBackendAPIError): ...


class FileReadError(BaseBackendAPIError): ...


class AnalyzeError(BaseBackendAPIError): ...


class AlreadyExistsError(BaseBackendAPIError): ...
